/* Unified artifact harness.
 * One run = tests + screenshots + GIFs + generated guide pages + README.
 * Media and docs are BUILD OUTPUT of verification: they cannot go stale
 * without the run failing. Regenerate with:  node tests/run.mjs
 */
import { chromium } from 'playwright';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MEDIA = path.join(ROOT, 'docs', 'media');
const GUIDE = path.join(ROOT, 'docs', 'guide');
const URL_ = 'file://' + path.join(ROOT, 'index.html');
const VP = { width: 390, height: 800 };

const { TOPICS } = await import('./topics.mjs');
fs.mkdirSync(MEDIA, { recursive: true });
fs.mkdirSync(GUIDE, { recursive: true });
for (const f of fs.readdirSync(MEDIA)) fs.rmSync(path.join(MEDIA, f));
for (const f of fs.readdirSync(GUIDE)) fs.rmSync(path.join(GUIDE, f));

const exe = process.env.CHROMIUM_PATH && fs.existsSync(process.env.CHROMIUM_PATH) ? process.env.CHROMIUM_PATH
  : (fs.existsSync('/opt/pw-browsers/chromium') ? '/opt/pw-browsers/chromium' : undefined);
const browser = await chromium.launch({ ...(exe ? { executablePath: exe } : {}), args: ['--no-sandbox'] });
const results = [];
let meta = null;

for (const topic of TOPICS) {
  const ctxOpts = { viewport: VP, hasTouch: true, isMobile: true, deviceScaleFactor: 2 };
  if (topic.video) ctxOpts.recordVideo = { dir: '/tmp/rmvid', size: VP };
  const context = await browser.newContext(ctxOpts);
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  if (topic.emulateMedia) await page.emulateMedia(topic.emulateMedia);
  await page.goto(URL_);
  await page.waitForTimeout(450);
  if (!topic.keepTour) await page.click('#tour-close').catch(() => {});
  await page.waitForTimeout(150);

  const cdp = await context.newCDPSession(page);
  const media = [];
  const c = {
    page, cdp,
    snap: async (suffix) => {
      const name = topic.id + (suffix ? '-' + suffix : '') + '.png';
      await page.screenshot({ path: path.join(MEDIA, name) });
      media.push(name);
    },
    nodeCenter: async (id) => {
      const b = await page.locator(`[data-node="${id}"]`).boundingBox();
      return { x: b.x + b.width / 2, y: b.y + b.height / 2 };
    },
    touchStart: (x, y) => cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] }),
    touchEnd: () => cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }),
    touchMove: async (x, y, steps = 1) => {
      for (let i = 1; i <= steps; i++) {
        await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y }] });
        await page.waitForTimeout(16);
      }
    },
  };

  let failures = [];
  try {
    await topic.drive(c);
    if (!media.length) await c.snap();
    failures = await topic.assert(c);
  } catch (e) {
    failures = ['harness error: ' + e.message];
  }
  failures.push(...errors.map((e) => 'pageerror: ' + e));

  // pull live truth for the README (single source: the running prototype)
  const snapshot = await page.evaluate(() => ({
    meters: { ...meters, costs: undefined, ttcs: undefined, jits: undefined },
    ipaMean: meters.costs.length ? meters.costs.reduce((a, b) => a + b, 0) / meters.costs.length : null,
    ttcP95: p95(meters.ttcs), jitP95: p95(meters.jits),
    chordMap: CHORD_MAP, vectorsVersion: VECTORS.version, vectorCount: VECTORS.cases.length,
    verbs: [...new Set(store.intents.map((i) => i.action))],
  })).catch(() => null);
  if (snapshot && !meta) meta = snapshot;

  const video = page.video?.();
  await context.close();   // flushes video
  let gif = null;
  if (topic.video && video) {
    const webm = await video.path();
    gif = topic.id + '.gif';
    execFileSync('ffmpeg', ['-y', '-i', webm, '-vf',
      'fps=12,scale=340:-1:flags=lanczos,split[a][b];[a]palettegen[p];[b][p]paletteuse',
      path.join(MEDIA, gif)], { stdio: 'ignore' });
  }
  results.push({ topic, failures, media, gif, snapshot });
  console.log(`${failures.length ? '✗' : '✓'} ${topic.id}${failures.length ? ' — ' + failures.join('; ') : ''}`);
}
await browser.close();

/* ---------- generate guide pages ---------- */
for (const r of results) {
  const lines = [
    `# ${r.topic.title}`, '',
    r.topic.prose, '',
    ...(r.gif ? [`![${r.topic.id}](../media/${r.gif})`, ''] : []),
    ...r.media.map((m) => `![${m}](../media/${m})`), '',
    `**Verified:** ${r.failures.length ? '✗ ' + r.failures.join('; ') : '✓ all assertions pass'}`, '',
    '*Generated by `tests/run.mjs` — edits here are overwritten; edit `tests/topics.mjs`.*', '',
  ];
  fs.writeFileSync(path.join(GUIDE, r.topic.id + '.md'), lines.join('\n'));
}

/* ---------- generate README ---------- */
const pass = results.filter((r) => !r.failures.length).length;
const chordRows = meta ? Object.entries(meta.chordMap).map(([w, v]) => `| \`${w}\` | \`${v}\` |`).join('\n') : '';
const q = results.find((r) => r.topic.id === 'quantized-commit')?.snapshot;
const ch = results.find((r) => r.topic.id === 'chord-input')?.snapshot;
const readme = `# radial-menu

Cross-platform radial menu for graph manipulation — served as a single-page
splash (\`index.html\`, zero dependencies) that **teaches itself**: the built-in
Tour is a linked list of actions that run live on the graph, ghost-finger and
all. Governed by the records in [docs/records](docs/records) under the qm
constitution; interpretive-governance notes for **g0** in
[docs/perspectives](docs/perspectives).

**Deploy:** every push runs \`tests/run.mjs\` in CI
([.github/workflows/pages.yml](.github/workflows/pages.yml)); only a green
harness publishes to GitHub Pages. The splash, its docs, and its media are one
build output — a red test means a stale page never ships.

**Vectors ${meta ? meta.vectorsVersion : '?'}: ${pass === results.length ? '✅' : '❌'} · topics ${pass}/${results.length} verified · conformance cases: ${meta?.vectorCount ?? '?'}**

The contract is the seam: a platform-neutral interaction contract plus
executable conformance vectors. This web prototype is the reference
implementation; Android/Compose is specified in
[docs/records/DRAFT-radial-menu-platform-plans.md](docs/records/DRAFT-radial-menu-platform-plans.md).

![release-select](docs/media/release-select.gif)

## Topics

Every row below is generated from one entry in \`tests/topics.mjs\` — the same
entry is the e2e test, the guide page, and the media producer.

| | Topic | Status |
|---|---|---|
${results.map((r) => `| ![${r.topic.id}](docs/media/${r.media[0]}) | [**${r.topic.title}**](docs/guide/${r.topic.id}.md) — ${r.topic.prose.split('. ')[0]}. | ${r.failures.length ? '✗' : '✓'} |`).join('\n')}

## Measured (this run)

| Metric | Value | Budget |
|---|---|---|
| IPA, chord verbs | 1 | 1 |
| TTC p95 (chord) | ${ch?.ttcP95 != null ? ch.ttcP95.toFixed(1) + ' ms' : '–'} | ≤ 16 ms |
| Grid jitter p95 | ${q?.jitP95 != null ? q.jitP95.toFixed(2) + ' ms' : '–'} | ≤ 1 ms |

## Chord vocabulary (extracted live from the prototype)

Prefix-free; a known word commits on its last keystroke. CharaChorder-class
devices hit these as single chords over plain HID.

| word | verb |
|---|---|
${chordRows}

## Layout

\`\`\`
index.html                the splash: demo + tour + meters, single file, no deps
conformance/vectors.json  executable half of the contract (v${meta?.vectorsVersion ?? '?'})
docs/records/             governed drafts (contract · metrics · platform plans · pipeline)
docs/perspectives/        g0 interpretive-governance notes
docs/guide/  docs/media/  GENERATED — never edit; every file is test output
tests/topics.mjs          the one registry: tests = docs = README = pics = vids
tests/run.mjs             the harness; \`node tests/run.mjs\` regenerates everything
.github/workflows/        CI: harness gates the Pages deploy
\`\`\`

## Accessibility (foundational, not bolted on)

Keyboard is a complete path: Tab reaches the graph, arrows walk node focus
geometrically, Enter opens the menu, arrows + Enter commit. The menu traps Tab
while open; wedges are labelled menuitems; highlight changes are announced to
a live region; \`prefers-reduced-motion\` collapses every animation (including
tour demos) to end states; touch targets respect a 44px floor; a skip link
jumps straight to the tour. The \`a11y-foundation\` and \`reduced-motion\`
topics above verify this on every run.

*README generated by \`tests/run.mjs\`. Numbers above are measurements, not
copy — if they are stale, the build is red.*
`;
fs.writeFileSync(path.join(ROOT, 'README.md'), readme);
console.log(`\n${pass}/${results.length} topics verified · README + ${results.length} guide pages + media regenerated`);
process.exit(pass === results.length ? 0 : 1);
