/* Regenerate index.html's inline VECTORS block from conformance/vectors.json.
 *
 * The JSON file is the governed artifact — the contract's "executable half",
 * the thing ports are judged against. The page carries an inline copy only so
 * it runs from file:// with no server and no fetch. Those two had already
 * diverged once (the file's traces carry per-event `t` timestamps the inline
 * copy had dropped) and nothing compared them, which made "conformant"
 * unfalsifiable for the reference implementation itself.
 *
 * So: this script generates, and tests/conformance.spec.mjs fails on drift.
 * Never hand-edit the block between the markers.
 *
 *   node scripts/sync-vectors.mjs            regenerate
 *   node scripts/sync-vectors.mjs --check    exit 1 if the file would change
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const HTML = path.join(ROOT, 'index.html');
const JSON_ = path.join(ROOT, 'conformance', 'vectors.json');

const BEGIN = '/* BEGIN GENERATED VECTORS';
const END = '/* END GENERATED VECTORS */';

const vectors = JSON.parse(fs.readFileSync(JSON_, 'utf8'));
const html = fs.readFileSync(HTML, 'utf8');

const block =
  `${BEGIN} — generated by scripts/sync-vectors.mjs from
 * conformance/vectors.json. Do not edit by hand; run \`npm run sync:vectors\`.
 * The JSON file is the governed artifact, this is a build product of it. */
const VECTORS = ${JSON.stringify(vectors, null, 2).split('\n').map((l, i) => (i ? '' : '') + l).join('\n')};
${END}`;

const i = html.indexOf(BEGIN);
const j = html.indexOf(END);
if (i === -1 || j === -1) {
  console.error('sync-vectors: generated markers not found in index.html.');
  console.error('Expected a block delimited by:\n  ' + BEGIN + ' ... */\n  ' + END);
  process.exit(2);
}
const next = html.slice(0, i) + block + html.slice(j + END.length);

if (process.argv.includes('--check')) {
  if (next !== html) {
    console.error('sync-vectors: index.html is out of date with conformance/vectors.json.');
    console.error('Run: npm run sync:vectors');
    process.exit(1);
  }
  console.log(`sync-vectors: in sync (v${vectors.version}, ${vectors.cases.length} cases)`);
  process.exit(0);
}

if (next === html) {
  console.log(`sync-vectors: already current (v${vectors.version}, ${vectors.cases.length} cases)`);
} else {
  fs.writeFileSync(HTML, next);
  console.log(`sync-vectors: index.html updated to v${vectors.version} (${vectors.cases.length} cases)`);
}
